const materialsByMode = {
    Painting: [
      "Brushes",
      "Acrylic Paints",
      "Oil Paints",
      "Watercolors",
      "Canvas",
      "Palette",
      "Easel",
      "Palette Knife",
      "Gesso",
      "Varnish",
    ],
    Sculpting: [
      "Clay",
      "Modeling Tools",
      "Wire",
      "Sculpting Knife",
      "Plaster",
      "Silicone Molds",
      "Wooden Modeling Tools",
      "Cutting Mat",
      "Sculpting Armature",
      "Polishing Tools",
    ],
    Drawing: [
      "Pencils",
      "Erasers",
      "Sketchpad",
      "Charcoal",
      "Blending Stumps",
      "Colored Pencils",
      "Fine Liners",
      "Markers",
      "Rulers",
      "Fixative Spray",
    ],
    Calligraphy: [
      "Calligraphy Pens",
      "Inks",
      "Special Paper",
      "Brush Pens",
      "Nib Holders",
      "Guideline Sheets",
      "Rulers for Layout",
      "Gold Ink",
      "Oblique Pen Holder",
      "Calligraphy Practice Pads",
    ],
    SoapMaking: [
      "Soap Base",
      "Essential Oils",
      "Dyes",
      "Silicone Molds",
      "Measuring Cups",
      "Double Boiler",
      "Thermometer",
      "Mixing Spoons",
      "Rubbing Alcohol Spray",
      "Packaging Materials",
    ],
    Mosaic: [
      "Glass Tiles",
      "Ceramic Tiles",
      "Tile Cutters",
      "Adhesive",
      "Grout",
      "Sponges",
      "Grouting Tools",
      "Gloves",
      "Mosaic Frames",
      "Sealer",
    ],
    Decoupage: [
      "Decoupage Paper",
      "Mod Podge",
      "Acrylic Paints",
      "Sandpaper",
      "Foam Brushes",
      "Scissors",
      "Sealer",
      "Gesso",
      "Wooden Items",
      "Varnish",
    ],
    JewelryMaking: [
      "Beads",
      "Wire",
      "Clasps",
      "Pliers Set",
      "Jewelry Findings",
      "Stringing Material",
      "Crimp Beads",
      "Gemstones",
      "Charms",
      "Wire Cutters",
    ],
    DigitalArt: [
      "Graphics Tablet",
      "Stylus",
      "Digital Art Software",
      "Color Calibration Tool",
      "High-Resolution Monitor",
      "Drawing Gloves",
      "Brush Packs",
      "Reference Images",
      "Keyboard Shortcuts Chart",
      "Cloud Storage",
    ],
    Photography: [
      "Camera",
      "Tripod",
      "Lighting Equipment",
      "Reflectors",
      "Backdrops",
      "Lenses",
      "Camera Bag",
      "Memory Cards",
      "Editing Software",
      "Filters",
    ],
    Weaving: [
      "Weaving Loom",
      "Warp Threads",
      "Weft Threads",
      "Shuttle",
      "Heddles",
      "Comb",
      "Scissors",
      "Weaving Needles",
      "Yarn",
      "Tension Device",
    ],
    CandleMaking: [
      "Wax (Soy, Beeswax, Paraffin)",
      "Wicks",
      "Fragrance Oils",
      "Dyes",
      "Candle Molds",
      "Double Boiler",
      "Thermometer",
      "Pouring Pitcher",
      "Glue Dots",
      "Wick Holders",
    ],
    Pyrography: [
      "Wood Burning Tool",
      "Wood Panels",
      "Carbon Paper",
      "Sandpaper",
      "Tips for Pyrography Tool",
      "Safety Gloves",
      "Rulers",
      "Stencils",
      "Design Templates",
      "Finishing Spray",
    ],
  };

  export default materialsByMode;